import type { InventoryTranslation } from "@/features/inventory/item-labels";
// Reviewed English spell and item names. UI qualifiers live in the dictionary.
export const buffProperNames: Record<string, string> = {
  "buffs.hymnOfHope": "Hymn of Hope",
  "buffs.handOfSalvation": "Hand of Salvation",
  "buffs.rapture": "Rapture",
  "debuffs.shadowEmbrace": "Shadow Embrace",
  "raidBuffs.giftOfTheWild": "Gift of the Wild",
  "raidBuffs.drumsOfTheWild": "Drums of the Wild",
  "buffs.blessingOfKings": "Greater Blessing of Kings",
  "raidBuffs.drumsOfForgottenKings": "Drums of Forgotten Kings",
  "buffs.blessingOfSanctuary": "Greater Blessing of Sanctuary",
  "raidBuffs.devotionAura": "Devotion Aura",
  "raidBuffs.stoneskinTotem": "Stoneskin Totem",
  "raidBuffs.scrollOfProtection": "Scroll of Protection VIII",
  "buffs.blessingOfMight": "Greater Blessing of Might",
  "raidBuffs.battleShout": "Battle Shout",
  "raidBuffs.abominationsMight": "Abomination's Might",
  "raidBuffs.unleashedRage": "Unleashed Rage",
  "raidBuffs.trueshotAura": "Trueshot Aura",
  "raidBuffs.bloodlust": "Bloodlust",
  "raidBuffs.sanctifiedRetribution": "Sanctified Retribution",
  "raidBuffs.arcaneEmpowerment": "Arcane Empowerment",
  "raidBuffs.ferociousInspiration": "Ferocious Inspiration",
  "buffs.renewedHope": "Renewed Hope",
  "buffs.vigilance": "Vigilance",
  "buffs.divineGuardians": "Divine Guardian",
  "buffs.painSuppressions": "Pain Suppression",
  "buffs.guardianSpirits": "Guardian Spirit",
  "raidBuffs.swiftRetribution": "Swift Retribution",
  "raidBuffs.moonkinAura": "Moonkin Aura",
  "raidBuffs.commandingShout": "Commanding Shout",
  "raidBuffs.bloodPact": "Blood Pact",
  "raidBuffs.arcaneBrilliance": "Arcane Brilliance",
  "raidBuffs.felIntelligence": "Fel Intelligence",
  "raidBuffs.scrollOfIntellect": "Scroll of Intellect VIII",
  "raidBuffs.leaderOfThePack": "Leader of the Pack",
  "raidBuffs.rampage": "Rampage",
  "raidBuffs.icyTalons": "Improved Icy Talons",
  "raidBuffs.windfuryTotem": "Windfury Totem",
  "buffs.blessingOfWisdom": "Greater Blessing of Wisdom",
  "raidBuffs.manaSpringTotem": "Mana Spring Totem",
  "buffs.vampiricTouch": "Vampiric Touch",
  "buffs.judgementsOfTheWise": "Judgements of the Wise",
  "buffs.huntingParty": "Hunting Party",
  "buffs.improvedSoulLeech": "Improved Soul Leech",
  "buffs.enduringWinter": "Enduring Winter",
  "raidBuffs.shadowProtection": "Prayer of Shadow Protection",
  "raidBuffs.natureResistanceTotem": "Nature Resistance Totem",
  "raidBuffs.aspectOfTheWild": "Aspect of the Wild",
  "raidBuffs.elementalOath": "Elemental Oath",
  "raidBuffs.wrathOfAirTotem": "Wrath of Air Totem",
  "raidBuffs.totemOfWrath": "Totem of Wrath",
  "raidBuffs.flametongueTotem": "Flametongue Totem",
  "raidBuffs.divineSpirit": "Divine Spirit",
  "raidBuffs.scrollOfSpirit": "Scroll of Spirit VIII",
  "raidBuffs.powerWordFortitude": "Power Word: Fortitude",
  "raidBuffs.scrollOfStamina": "Scroll of Stamina VIII",
  "raidBuffs.strengthOfEarthTotem": "Strength of Earth Totem",
  "raidBuffs.hornOfWinter": "Horn of Winter",
  "raidBuffs.scrollOfAgility": "Scroll of Agility VIII",
  "raidBuffs.scrollOfStrength": "Scroll of Strength VIII",
  "raidBuffs.retributionAura": "Retribution Aura",
  "partyBuffs.braidedEterniumChain": "Braided Eternium Chain",
  "partyBuffs.chainOfTheTwilightOwl": "Chain of the Twilight Owl",
  "partyBuffs.heroicPresence": "Heroic Presence",
  "partyBuffs.eyeOfTheNight": "Eye of the Night",
  "raidBuffs.thorns": "Thorns",
  "partyBuffs.manaTideTotems": "Mana Tide Totem",
  "buffs.innervates": "Innervate",
  "buffs.powerInfusions": "Power Infusion",
  "buffs.focusMagic": "Focus Magic",
  "buffs.tricksOfTheTrades": "Tricks of the Trade",
  "buffs.unholyFrenzy": "Unholy Frenzy",
  "debuffs.sunderArmor": "Sunder Armor",
  "debuffs.exposeArmor": "Expose Armor",
  "debuffs.acidSpit": "Acid Spit",
  "debuffs.faerieFire": "Improved Faerie Fire",
  "debuffs.curseOfWeakness": "Curse of Weakness",
  "debuffs.sting": "Sting",
  "debuffs.sporeCloud": "Spore Cloud",
  "debuffs.vindication": "Vindication",
  "debuffs.demoralizingShout": "Demoralizing Shout",
  "debuffs.demoralizingRoar": "Demoralizing Roar",
  "debuffs.demoralizingScreech": "Demoralizing Screech",
  "debuffs.mangle": "Mangle (Bear)",
  "debuffs.trauma": "Trauma",
  "debuffs.stampede": "Stampede",
  "debuffs.totemOfWrath": "Totem of Wrath",
  "debuffs.heartOfTheCrusader": "Heart of the Crusader",
  "debuffs.masterPoisoner": "Master Poisoner",
  "debuffs.thunderClap": "Thunder Clap",
  "debuffs.frostFever": "Frost Fever",
  "debuffs.judgementsOfTheJust": "Judgements of the Just",
  "debuffs.infectedWounds": "Infected Wounds",
  "debuffs.insectSwarm": "Insect Swarm",
  "debuffs.scorpidSting": "Scorpid Sting",
  "debuffs.bloodFrenzy": "Blood Frenzy",
  "debuffs.savageCombat": "Savage Combat",
  "debuffs.shadowMastery": "Improved Shadow Bolt",
  "debuffs.improvedScorch": "Improved Scorch",
  "debuffs.wintersChill": "Winter's Chill",
  "debuffs.misery": "Misery",
  "debuffs.ebonPlaguebringer": "Ebon Plaguebringer",
  "debuffs.earthAndMoon": "Earth and Moon",
  "debuffs.curseOfElements": "Curse of the Elements",
  "debuffs.judgementOfWisdom": "Judgement of Wisdom",
  "debuffs.judgementOfLight": "Judgement of Light",
  "buffs.shatteringThrows": "Shattering Throw",
  "debuffs.giftOfArthas": "Gift of Arthas",
  "debuffs.crystalYield": "Crystal Yield",
  "buffs.handOfSacrifices": "Hand of Sacrifice",
  "raidBuffs.frostResistanceAura": "Frost Resistance Aura",
  "raidBuffs.frostResistanceTotem": "Frost Resistance Totem",
  "raidBuffs.strengthOfWrynn": "Strength of Wrynn",
  "debuffs.huntersMark": "Hunter's Mark",
  "partyBuffs.atieshMage": "Atiesh (Mage)",
  "partyBuffs.atieshWarlock": "Atiesh (Warlock)",
};
export const buffLabelKeys: Record<string, string> = {
  "raidBuffs.demonicPactSp": "buffs.labels.demonicPactSp",
  "buffs.revitalizeRejuvination": "buffs.labels.revitalizeRejuvination",
  "buffs.revitalizeWildGrowth": "buffs.labels.revitalizeWildGrowth",
};
export function buffLabel(
  group: string,
  field: string,
  t: InventoryTranslation,
) {
  const key = `${group}.${field}`;
  return buffLabelKeys[key]
    ? t(buffLabelKeys[key])
    : (buffProperNames[key] ?? t("buffs.unknown"));
}

export const consumeFallbackNames: Record<string, string> = {
  "proto.PetFood.2": "Kibler’s Bits",
};
